class Config(object):
    def __init__(self,
                 embedding_dimension=256,
                 training_epoch=50,
                 num_val=1,
                 max_mr_length=80,
                 max_sentence_length=80,
                 learning_rate=0.01,
                 batch_size=128,
                 dropout=0.1,
                 encoder_input_size=256,
                 encoder_hidden_size=512,
                 decoder_input_size=512,
                 decoder_hidden_size=512,
                 checkpoint_path='../checkpoint/',
                 root_path='../e2e_dataset/',
                 vocab_path='vocab.npy',
                 train_data_path='trainset.csv',
                 dev_data_path='devset.csv',
                 test_data_path='testset.csv',
                 test_result_path='./result.txt'):
        self.embedding_dimension = embedding_dimension  # 词向量的维度
        self.epoch = training_epoch  # 训练轮数
        self.num_val = num_val  # 经过几轮才开始验证
        self.max_mr_length = max_mr_length  # 最大结构化文本长度
        self.max_sentence_length = max_sentence_length  # 句子最大长度
        self.lr = learning_rate  # 学习率
        self.batch_size = batch_size  # 批大小
        self.dropout = dropout  # dropout概率
        self.encoder_input_size = encoder_input_size
        self.encoder_hidden_size = encoder_hidden_size
        self.decoder_input_size = decoder_input_size
        self.decoder_hidden_size = decoder_hidden_size
        self.checkpoint_path = checkpoint_path
        self.root_path = root_path
        self.vocab_path = vocab_path
        self.train_data_path = train_data_path
        self.dev_data_path = dev_data_path
        self.test_data_path = test_data_path
        self.test_result_path = test_result_path
